import math

TABLE_SIZE = 1024
AMPLITUDE = 32767  # fixed-point scale

COMMENT = """\
This file is a part of Popcorn OS.

This file was generated by pop_trig_h.py. Don't
change this file; something might break!\
"""

with open("pop_trig.h", "w") as f:
    f.write(f"/*\n{COMMENT}\n*/\n\n")
    f.write("#pragma once\n\n")
    f.write(f"#define TABLE_SIZE {TABLE_SIZE}\n")
    f.write(f"#define AMPLITUDE {AMPLITUDE}\n\n")

    # Sine table
    f.write("static const short int sin_table[TABLE_SIZE] = {\n")
    for i in range(TABLE_SIZE):
        angle = (2.0 * math.pi * i) / TABLE_SIZE
        val = int(AMPLITUDE * math.sin(angle))
        f.write(f"{val},")
        if i % 16 == 15: f.write("\n")
    f.write("};\n\n")

    # Cosine table
    f.write("static const short int cos_table[TABLE_SIZE] = {\n")
    for i in range(TABLE_SIZE):
        angle = (2.0 * math.pi * i) / TABLE_SIZE
        val = int(AMPLITUDE * math.cos(angle))
        f.write(f"{val},")
        if i % 16 == 15: f.write("\n")
    f.write("};\n")